spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  # Routes for Employee Service
#  cloud:
#    gateway:
#      routes[0]:
#        id: EMPLOYEE-SERVICE
#        uri: lb://EMPLOYEE-SERVICE
#        predicates[0]: Path=/api/employee/**
#      routes[1]:
#        id: DEPARTMENT-SERVICE
#        uri: lb://DEPARTMENT-SERVICE
#        predicates[0]: Path=/api/department/**

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 9191
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: DEBUG
